# Generated by Django 4.0.3 on 2022-03-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniacco_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
            ],
        ),
    ]
